language: ruby
rvm:
  - 2.5.3
addons:
  code_climate:
      repo_token: $CODE_CLIMATE_TEST_REPORTER_ID
services:
  - postgresql
before_install:
  - gem update bundler
bundler_args: --without production

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - bundle exec rails db:setup RAILS_ENV=test
  - bundle exec rspec

after_success:
  - bundle exec codeclimate-test-reporter
